### PR TITLE
Update build and workflows

### PR DESCRIPTION
**Pull request by smiet**
Hi @zhucaoxiang 

Updated the build system to use mesonpy, much more futureproof and compatible with numpy2.0. 

Got it to compile the fortran biot-savart.py extensions, but they dont seem to be correctly implemented... maybe this part of the code is deprecated?

try in test/coil
```python
from coilpy import Coil
import numpy as np

ellipse = Coil.read_makegrid("ellipse.coils")
ellipse.bfield(np.random.random(3))

>>>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 ellipse.bfield(np.random.random(3))

File ~/miniconda3/envs/test/lib/python3.10/site-packages/coilpy/coils.py:868, in Coil.bfield(self, pos, method)
    866 for icoil in list(self):
    867     func = getattr(icoil, method)
--> 868     mag += func(pos)
    869 return mag

File ~/miniconda3/envs/test/lib/python3.10/site-packages/coilpy/coils.py:122, in SingleCoil.hanson_hirshman(self, pos)
    119 from coilpy_fortran import hanson_hirshman
    121 xyz = np.transpose([self.x, self.y, self.z])
--> 122 return hanson_hirshman(pos, xyz, self.I)

TypeError: coilpy_fortran.hanson_hirshman() missing required argument 'bfield' (pos 4)
```

Anyhows, there is probably a lot more to do to fix the build and pypi push.

### CODE REVIEW

**Comment by zhucaoxiang** [comment]
@smiet Thanks for your contribution. The Fortran part was working. There may have been something changed. If you don't have time, I am okay with fixing the fortran part later. 
The tests are failing. Do you want to take a look at them? I can also try to fix them, but probably have to wait until next week.

**Comment by smiet** [comment]
Ah! switching to meson requirements is not needed, and I removed it, but forgot it was hard-coded in the build workflow. 

Have to go home now, will try tomorrow to fix, unless you feel like it (removing should work, pip install should do everything)

**Comment by smiet** [comment]
Hi @zhucaoxiang the install runs correctly on the runner now, but the labeler and the documentation upload are failing. I do not know if the pypi build works, I made some changes and updated the versions of the actions, but in the publish workflow `actions/labeler@v2` seems deprecated. 

I leave those to you to fix. 

re: fortran method: I think I corrupted my python environment before, the code now works for 1method=hanson_hirshman` (the `method=biot_savart` still fails with `AttributeError: 'SingleCoil' object has no attribute 'dt'`

If you can adapt the publish (and also pypi) steps, we are good to go, and after merge I can point `py_spec` to this version of `coilpy`

**Comment by zhucaoxiang** [comment]
@smiet Thanks for your contribution. I will merge for now. 

AttributeError: 'SingleCoil' object has no attribute 'dt'`
It would help if you computed the tangent first via `SingleCoil.fourier_tangent` or `SingleCoil.spline_tangent`.

**Pull request merged**
